# Lab | Inferential statistics - ANOVA

## Part 1

In this activity, we will look at another example. Your task is to understand the problem and write down all the steps to set up ANOVA. After the next lesson, we will ask you to solve this problem using Python. Here are the steps that you would need to work on: - Null hypothesis - Alternate hypothesis - Level of significance - Test statistic - P-value - F table

## Context

Suppose you are working as an analyst in a microprocessor chip manufacturing plant. You have been given the task of analyzing a plasma etching process with respect to changing Power (in Watts) of the plasma beam. Data was collected and provided to you to conduct statistical analysis and check if changing the power of the plasma beam has any effect on the etching rate by the machine. You will conduct ANOVA and check if there is any difference in the mean etching rate for different levels of power. You can find the data anova_lab_data.xlsx file in the files_for_lab folder

- State the null hypothesis
- State the alternate hypothesis
- What is the significance level
- What are the degrees of freedom of model, error terms, and total DoF

Data was collected randomly and provided to you in the table as shown: link to the image - Data

- Importing the libraries

In [10]:
import pandas as pd
import numpy as np
from scipy import stats
import statsmodels.api as sm
from statsmodels.formula.api import ols

import warnings
warnings.filterwarnings('ignore')

- Loading the data

In [2]:
df = pd.read_excel('anova_lab_data.xlsx')
print (df)

   Power   Etching Rate
0   160 W          5.43
1   180 W          6.24
2   200 W          8.79
3   160 W          5.71
4   180 W          6.71
5   200 W          9.20
6   160 W          6.22
7   180 W          5.98
8   200 W          7.90
9   160 W          6.01
10  180 W          5.66
11  200 W          8.15
12  160 W          5.59
13  180 W          6.60
14  200 W          7.55


In [7]:
#removing the space
df.columns = df.columns.str.replace(' ', '')

In [8]:
print (df)

   Power_  Etching_Rate
0   160 W          5.43
1   180 W          6.24
2   200 W          8.79
3   160 W          5.71
4   180 W          6.71
5   200 W          9.20
6   160 W          6.22
7   180 W          5.98
8   200 W          7.90
9   160 W          6.01
10  180 W          5.66
11  200 W          8.15
12  160 W          5.59
13  180 W          6.60
14  200 W          7.55


- State the null hypothesis

The null is that changing the power of the bean does not have effect on the mean etching rate

- State the alternate hypothesis

The alternate is that changing the power of the bean has an effect this time

- What is the significance level

The standard is α = 0.05, which signifies a 5% chance of error

- What are the degrees of freedom of model, error terms, and total DoF

Degrees of freedom model : for x number of compared objects, we have to do x-1, so in this case 2 because we have 3 power levels (160, 180, 200)

Error terms : the number of notes, here 15, minus x, the number of compared objects, so 12

Total DoF : the number of notes minus 1, so here 14

## Part 2

- In this section, use Python to conduct ANOVA.
- What conclusions can you draw from the experiment and why?

In [11]:
df = pd.DataFrame({
    'Power': ['160 W', '180 W', '200 W', '160 W', '180 W', '200 W', '160 W', '180 W', '200 W', '160 W', '180 W', '200 W', '160 W', '180 W', '200 W'],
    'Etching_Rate': [5.43, 6.24, 8.79, 5.71, 6.71, 9.20, 6.22, 5.98, 7.90, 6.01, 5.66, 8.15, 5.59, 6.60, 7.55]
})

In [13]:
#anova
model = ols('Etching_Rate ~ C(Power)', data=df).fit()
anova = sm.stats.anova_lm(model)

In [14]:
print(anova)

            df     sum_sq   mean_sq          F    PR(>F)
C(Power)   2.0  18.176653  9.088327  36.878955  0.000008
Residual  12.0   2.957240  0.246437        NaN       NaN


We can see that  changing the power of the plasma beam has a significant effect on the mean etching rate. The p-value is 0.000008 so less than our significance level. We can therefore reject the null. 